Feat/new components
nasa-jpl/react-stellar pull request #28
Opened 2023-05-22 15:48 UTC by AaronPlave

Adds several new components:

- [ ] WIP navbar

2023-05-30 02:26 UTC, anilnatha commented
Hey @AaronPlave, thanks for taking the time to add these components, these look great!

I spent a little time reviewing them in storybook and was wondering if the following items require an update:

### Switch

1. The `labelPosition` values are rendering the opposite of what is chosen. In other words, when one chooses `left`, the label is on the right.

<img width="1036" alt="Screen Shot 2023-05-29 at 19 16 22" src="https://github.com/nasa-jpl/react-stellar/assets/931107/fd13afd7-ba52-42a5-87bc-0a8ab1f45000">

2. I see that the component's width is inherited the parent container; however, a flex width spacing is used between the label and the switch when `labelPosition="right"`; however, when the `labelPosition="left"`, the label and switch are placed next to each other. My thought is that they should always be next to one another. Also, should their width be inherited from their parent container or should the switch's contents dictate their width?

<img width="1040" alt="Screen Shot 2023-05-29 at 19 16 50" src="https://github.com/nasa-jpl/react-stellar/assets/931107/4154f97a-ca75-4abf-bbdb-cec9c6e48f27">

### Avatar

1. Perhaps the typography sizing should scale up when the `large` version is used? At the moment both avatar sizes use the same type size.

2023-05-30 15:50 UTC, AaronPlave commented
**Switch**
1. Good catch on label position - I'll fix that for Switch and Checkbox. 
2. For the situation where text is left, toggle is right, the Stellar figma design specifies that the width be defined by the parent element. https://www.figma.com/file/a696svN2S7YNlZRYAkeLob/Stellar-Design-System?type=design&node-id=5441-7943&t=tLux7kDqdl3Ig71o-4. I think the idea behind this is to maintain a consistent positioning of the right-side toggle in a list of switches/checkboxes/radios. The stories for Switch and Checkbox present their components in a sort of unusual fashion, maybe it'd be useful to constrain the parent width in the stories to show intended use?

2023-05-30 16:51 UTC, anilnatha commented
Hey @AaronPlave , regarding your comments:

> maybe it'd be useful to constrain the parent width in the stories to show intended use?

I think this would be helpful.

>One argument against larger text size here would be that large buttons in Stellar don't have larger text size. Guess it depends on where this large avatar will be used. Could alternatively just get rid of the large size until we have a spec?

Hmm, is there a design requirement to not scale the font on the larger buttons? I could imagine that the typography should scale when buttons do.  I'm good with hiding the large size until we have a spec or consensus on how components across the design system should behave when their size is increased or decreased.

2023-05-30 17:51 UTC, rtapella commented
Do we need a "logged out" navbar? eg. with a `Log in` button in place of the avatar menu?

2023-05-30 18:45 UTC, AaronPlave commented
> Do we need a "logged out" navbar? eg. with a `Log in` button in place of the avatar menu?
> 
> 

Some applications may but don't think stellar necessarily needs to ship that. Seems fairly application specific and the navbar is designed to let you put whatever content you want inside of it. The navbar in the story isn't a single component but instead a collection of stellar and components plus some custom content from the story, similar to how an application would compose a navbar for specific use.

2023-05-30 18:48 UTC, rtapella commented
Also... in mobile mode, does it make sense to show the account/login button + the hamburger?

2023-05-30 20:19 UTC, duranb requested changes

2023-05-30 20:19 UTC, duranb commented on src/components/Avatar/Avatar.tsx
> +} & AlertDialog.DialogProps;
Does `AlertDialog` need to be imported? If not, I'm probably just not seeing what is putting the namespace on the global scope.

2023-05-30 20:29 UTC, AaronPlave commented on src/components/Avatar/Avatar.tsx
> +} & AlertDialog.DialogProps;
Whoops! Good catch, came from duplicated component, will fix.

2023-05-30 20:30 UTC, AaronPlave commented
> Also... in mobile mode, does it make sense to show the account/login button + the hamburger?

It might? Happy to include it in the example though wasn't sure if it might have a different design?

2023-05-31 21:17 UTC, anilnatha commented
@AaronPlave I pulled down your recent changes and reviewed them. Thanks for fixing the label placement issue for the Switch/Toggle component, looks good!

On the Navbar and Menu components, there appears to be an issue with the foreground color for the typography and icon? They show as light color which is very hard to discern. Apologies if you're already working on a resolution for this.

2023-06-05 16:43 UTC, duranb commented
> On the Navbar and Menu components, there appears to be an issue with the foreground color for the typography and icon? They show as light color which is very hard to discern. Apologies if you're already working on a resolution for this.

@anilnatha I think that might be part of a separate issue that'll need to be addressed in the stellar library itself. The "dark" CSS theme has background/text color specifications that are both light. Can you confirm if you're using the dark mode theme in your storybook preview? If so, do you mind switching to light mode and seeing if it's still too light?

2023-06-05 17:11 UTC, anilnatha commented
> > On the Navbar and Menu components, there appears to be an issue with the foreground color for the typography and icon? They show as light color which is very hard to discern. Apologies if you're already working on a resolution for this.
> 
> @anilnatha I think that might be part of a separate issue that'll need to be addressed in the stellar library itself. The "dark" CSS theme has background/text color specifications that are both light. Can you confirm if you're using the dark mode theme in your storybook preview? If so, do you mind switching to light mode and seeing if it's still too light?

@duranb Thanks for the summary of what the issue may be. I was using the dark mode when viewing the changes and verified that the issue is specific to that as evidenced by these screenshots:

### Dark Mode — menu icon not visible

<img width="1483" alt="image" src="https://github.com/nasa-jpl/react-stellar/assets/931107/cc7abff5-705f-4a9a-a887-6de76228536c">

### Light Mode — menu icon is now visible

<img width="1483" alt="image" src="https://github.com/nasa-jpl/react-stellar/assets/931107/6a5a22f3-e324-4398-94ec-ace3e87eb6bc">

2023-06-05 17:50 UTC, AaronPlave commented
Dark theming isn't built out for react-stellar yet 😅 but we'll get there in a separate effort.

2023-06-05 17:52 UTC, anilnatha commented
Right, I remember you mentioning that. So that last issue I reported can be pushed off. I need to be mindful of running this in light mode. My apologies.

2023-06-05 18:09 UTC, AaronPlave commented
Any other comments on this PR?

2023-06-05 18:21 UTC, duranb commented
> @duranb Thanks for the summary of what the issue may be. I was using the dark mode when viewing the changes and verified that the issue is specific to that as evidenced by these screenshots:

@anilnatha Thank you for verifying!

2023-06-05 18:26 UTC, anilnatha commented
> Any other comments on this PR?

None from me.

2023-06-05 18:28 UTC, anilnatha approved these changes

2023-06-05 18:41 UTC, duranb approved these changes

2023-06-05 18:43 UTC, merged