Slider
nasa-jpl/react-stellar pull request #42
Opened 2023-10-04 23:35 UTC by AaronPlave

Implements the Slider component based off the Radix Slider component. One special note here is that the Slider must be controlled by the parent state in order for the text inputs to function. The only way to have this component function uncontrolled is to set `showInputs` to `false`. 

<img width="431" alt="image" src="https://github.com/nasa-jpl/react-stellar/assets/4419607/243671f4-2157-4a60-9dfd-d0fa54e095a2">

2023-10-05 17:40 UTC, duranb requested changes

2023-10-05 17:40 UTC, duranb commented on src/components/Slider/Slider.stories.tsx
> +export const WithRange: Story = {
Does it make sense to name the story as `WithRangeShown` or something similar? I kept thinking that this showcased that the range was being limited in some way and couldn't figure out how it was different from the others haha

2023-10-09 15:18 UTC, AaronPlave commented on src/components/Slider/Slider.stories.tsx
> +export const WithRange: Story = {
Changed!

2023-10-09 15:50 UTC, duranb approved these changes
lgtm!

2023-10-09 16:17 UTC, merged